spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/api/user/**
          
      - id: forum-service
        uri: lb://FORUM-SERVICE
        predicates:
          - Path=/api/forum/**

      - id: comment-service
        uri: lb://COMMENT-SERVICE
        predicates:
          - Path=/api/comment/**

      - id: tag-service
        uri: lb://TAG-SERVICE
        predicates:
          - Path=/api/tag/**

      - id: chart-service
        uri: lb://CHART-SERVICE
        predicates:
          - Path=/api/chart/**

      - id: mail-service
        uri: lb://MAIL-SERVICE
        predicates:
          - Path=/api/mail/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

server:
  port: 8080
  